#ifndef _GUI_H
#define _GUI_H

#define DEFAULT_CENTER_WIDTH 300
#define DEFAULT_CENTER_TEXT_HEIGHT 300
#define DEFAULT_COLUMN_WIDTH 200
#define GRID_COLUMN_SPACING 5
#define GRID_ROW_SPACING 2
#define WINDOW_BORDER_SIZE 5

#define INIT_WINDOW_WIDTH 250
#define INIT_WINDOW_HEIGHT 200
#define INIT_WINDOW_SPACING 2

#define MAX_INPUT_LEN 1024

void gui_init();

#endif
